import { NgZone, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { AngularGooglePlaceService } from '../services/index';
import { Address } from '../models/index';
export declare class AngularGooglePlaceDirective implements OnInit {
    private el;
    private service;
    private ngZone;
    changelogs: Array<string>;
    options: any;
    CountryCodes: EventEmitter<any>;
    TypesOptions: EventEmitter<any>;
    setAddress: EventEmitter<any>;
    FormatAddress: EventEmitter<any>;
    street_number: EventEmitter<any>;
    postal_code: EventEmitter<any>;
    country: EventEmitter<any>;
    lat: EventEmitter<any>;
    lng: EventEmitter<any>;
    adr_address: EventEmitter<any>;
    formatted_address: EventEmitter<any>;
    name: EventEmitter<any>;
    place_id: EventEmitter<any>;
    types: EventEmitter<any>;
    url: EventEmitter<any>;
    utc_offset: EventEmitter<any>;
    vicinity: EventEmitter<any>;
    photos: EventEmitter<any>;
    street: EventEmitter<any>;
    city: EventEmitter<any>;
    state: EventEmitter<any>;
    district: EventEmitter<any>;
    autocomplete: any;
    trigger: any;
    place: Address;
    constructor(el: ElementRef, service: AngularGooglePlaceService, ngZone: NgZone);
    onFocus(target: any): void;
    ngOnInit(): void;
    setAutocompleteAndInvokeEvent(options: any): void;
    invokeEvent(): void;
}
